import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/widgets/header/ui/Header";
import Footer from "@/widgets/footer/ui/Footer";
import { routesData } from "@/widgets/header/lib/routesData";
import StoreProvider from "@/app/StoreProvider";
import "./styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <header>
            <Header navigation={routesData} />
          </header>
          <main className="flex justify-center border border-gray-300">
            <section className="border border-gray-950 w-[1200px]">
              {children}
            </section>
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </StoreProvider>
    </html>
  );
}
