import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/widgets/header/ui/Header";
import Footer from "@/widgets/footer/ui/Footer";
import { routesData } from "@/widgets/header/lib/routesData";
import StoreProvider from "@/app/StoreProvider";
import "./styles/globals.scss";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <header className="mb-3">
            <Header navigation={routesData} />
          </header>
          <main className="flex justify-center">
            <section className="w-[800px]">{children}</section>
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </StoreProvider>
    </html>
  );
}
